local:
  server:
    port: 8080
spring:
  application:
    name: Study-System
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

task:
  delete-old-schedules:
    cron: 0 0 0 * * *
