services:
  postgres:
    image: postgres:latest
    container_name: docker-app-postgres-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
